### ISSUE TITLE
"generic" plugins are currently sorted into the "unsupported" package

### ISSUE THREAD

**Issue by danwinship** [openshift/containernetworking-plugins#9]
The split between "supported" and "unsupported" is kind of weird. In particular, `loopback` is being sorted into "unsupported" even though it's critical to the functioning of the system...

IIRC, openshift-sdn currently installs its own builds of `loopback` and `host-local`, but it should probably be getting them from this repo instead, for consistency?

This came up in the discussion of kuryr in https://github.com/openshift/cluster-network-operator/pull/18. Where should they be getting `loopback`, etc, from? It seems good to say that they should be getting it from an official `container-networking-plugins` package, but bad to say that it should be from `container-networking-plugins-unsupported`...

@dcbw @dulek @squeed

**Comment by danwinship** [comment]
Actually, given that we copy all of the plugins in to the same place anyway, does it even make sense to split them into separate "supported" and "unsupported" images? I mean, I get why we want to have "supported" and "unsupported" plugins, but is dividing them into separate images the right way to communicate the split, given that nobody ever actually sees those images except us?

**Comment by dougbtv** [comment]
@danwinship , great points.

> does it even make sense to split them into separate "supported" and "unsupported" images?

I don't believe it does make sense. Actually due to your input at some point during some troubleshooting... I had mentioned that the "loopback was unsupported" [in that it was in the -unsupported image] and you were saying "That... created every loopback in every pod!" and that definitely struck a chord with me. The -supported and -unsupported container images have only caused confusion. Given that feedback we decided to condense into a single "container-networking-plugins" (without an -unsupported or -supported designation), as you're right... It's an ineffective way to communicate it, it's even provided a fair bit of consternation to QE during their validation, as well.

I have a PR open here #8 -- for updating to v0.8.1 tagged reference plugins, as well as updating so it builds from a single image. I need to file for a new container image, and I'll also try to make a PR to the cluster-network-operator to use the single image.

If you can use the `loopback` & `host-local` from that install that's great, if not... Please let me know if there's anything I can do to assist there, for sure.

**Comment by danwinship** [comment]
Fixed by #8
